os: linux
language: minimal
services:
- docker
before_install:
- echo "hello"
jobs:
  include:
  - stage: Test
    name: Build and test the current version of the application using Docker
    env:
    - RAILS_ENV=test
    script: |
      echo "==== testing terrafrom ===="
      git clone https://github.com/tfutils/tfenv.git ~/.tfenv
      export PATH="$HOME/.tfenv/bin:$PATH"
      /bin/bash install-terraform-provider-for-cf.sh
      cd terraform
      tfenv install
      ls -la ~/.terraform.d/plugins/
      ls -la ~/.terraform.d/plugins/linux_amd64/
      echo "terraform init"
      terraform init
      echo "terrform fmt"
      terraform fmt  -diff -check -recursive
      echo "terraform validate"
      terraform validate
      echo $?
      echo "finished stuff"
deploy:
- provider: script
  script: bash travis-docker-push.sh
  on:
    all_branches: true
- provider: script
  script: bash deploy-terraform.sh
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^(develop|master)$
env:
  global:
    secure: mBNvcyOEhYVAbbUJL4sXvwU6RM9LgFLAaEq/B5VKhUSOSKWvcYYInk5qWOldMF79aE8mC7JsOi5D4AC6fvPEEU2aM9N5jcvoNyR5FEKg80ltgK8GE8NwrzqjD3shS2IhFtKdBN1PI/vDxAtIJqefQ8eSy2/FwdpN/aB06QDGjEy5ye2dh/A4YH5fAz1W9lncFI8zr7ZdPC5N7FG6DkNCVju9wfqwzyHCQabuJ3iKvq3dxBaRvJgrIi6I2QVHV9ieWARuI5CHgYQWwm2VPVW5vUhrZ3ZaefD5qJZ4Bp+NzlnDH7frCjuDpPrCiNI6wYrbOxj4LFVDAWl9dMYcZ9BY6DNQjeTtSt9qLCgG6csBsTf9RHR5THz3zreChEyf/+iJvBqyh9XdSNj/ZtEDFAM4z4LTsyQy7VlxyjLoO+oYOONzQP/y4EOmELJ7YPvB6bZmazJ2Rpix91svlBmaxtcx63W0aZa8yqqzJ5n6mPdIIBnMQOlNkofUSapaKJRceMcVqHk/5EqjUG7ETTf8eohrfLqrHP/S344NPNCDMHmTIoWd4QL7K9E0IeAinBUOa8RfN4A3SfXvouOPvfZGqCjmciAsQi2r024EqZ/c39xu1BQDLIm+LZ9ThMBimi2u7yZV7W4ijoY7DRae3mgzqGxnHxEmWhtDMWWnEujfR2BM4oY= # Coveralls READ_TOKEN
