#!/usr/bin/env ruby

tests = Dir["spec/**/*_spec.rb"]
  .sort.
  # Add randomization seed based on SHA of each commit
  shuffle(random: Random.new(ENV["GITHUB_SHA"].to_i(16)))
  .select
  .with_index { |el, i|
    i % ENV["CI_NODE_TOTAL"].to_i == ENV["CI_NODE_INDEX"].to_i
  }

exec "bundle exec rspec -f d #{tests.join(" ")}"
